/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as AdminStokRouteImport } from './routes/admin.stok'
import { Route as AdminProdukRouteImport } from './routes/admin.produk'
import { Route as AdminPesanRouteImport } from './routes/admin.pesan'
import { Route as AdminPembayaranRouteImport } from './routes/admin.pembayaran'
import { Route as AdminPanduanRouteImport } from './routes/admin.panduan'
import { Route as AdminOrderRouteImport } from './routes/admin.order'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminArtikelRouteImport } from './routes/admin.artikel'
import { Route as SiteTentangRouteImport } from './routes/_site.tentang'
import { Route as SiteLacakRouteImport } from './routes/_site.lacak'
import { Route as SiteKontakRouteImport } from './routes/_site.kontak'
import { Route as SiteKeranjangRouteImport } from './routes/_site.keranjang'
import { Route as SiteProdukIndexRouteImport } from './routes/_site.produk.index'
import { Route as SiteArtikelIndexRouteImport } from './routes/_site.artikel.index'
import { Route as SiteProdukSlugRouteImport } from './routes/_site.produk.$slug'
import { Route as SiteOrderIdRouteImport } from './routes/_site.order.$id'
import { Route as SiteArtikelSlugRouteImport } from './routes/_site.artikel.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AdminStokRoute = AdminStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdukRoute = AdminProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPesanRoute = AdminPesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPembayaranRoute = AdminPembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanduanRoute = AdminPanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrderRoute = AdminOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtikelRoute = AdminArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => AdminRoute,
} as any)
const SiteTentangRoute = SiteTentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLacakRoute = SiteLacakRouteImport.update({
  id: '/lacak',
  path: '/lacak',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKontakRoute = SiteKontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKeranjangRoute = SiteKeranjangRouteImport.update({
  id: '/keranjang',
  path: '/keranjang',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProdukIndexRoute = SiteProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArtikelIndexRoute = SiteArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProdukSlugRoute = SiteProdukSlugRouteImport.update({
  id: '/produk/$slug',
  path: '/produk/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrderIdRoute = SiteOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArtikelSlugRoute = SiteArtikelSlugRouteImport.update({
  id: '/artikel/$slug',
  path: '/artikel/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/keranjang': typeof SiteKeranjangRoute
  '/kontak': typeof SiteKontakRoute
  '/lacak': typeof SiteLacakRoute
  '/tentang': typeof SiteTentangRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/order': typeof AdminOrderRoute
  '/admin/panduan': typeof AdminPanduanRoute
  '/admin/pembayaran': typeof AdminPembayaranRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/admin/stok': typeof AdminStokRoute
  '/admin/': typeof AdminIndexRoute
  '/artikel/$slug': typeof SiteArtikelSlugRoute
  '/order/$id': typeof SiteOrderIdRoute
  '/produk/$slug': typeof SiteProdukSlugRoute
  '/artikel/': typeof SiteArtikelIndexRoute
  '/produk/': typeof SiteProdukIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/keranjang': typeof SiteKeranjangRoute
  '/kontak': typeof SiteKontakRoute
  '/lacak': typeof SiteLacakRoute
  '/tentang': typeof SiteTentangRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/order': typeof AdminOrderRoute
  '/admin/panduan': typeof AdminPanduanRoute
  '/admin/pembayaran': typeof AdminPembayaranRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/admin/stok': typeof AdminStokRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/artikel/$slug': typeof SiteArtikelSlugRoute
  '/order/$id': typeof SiteOrderIdRoute
  '/produk/$slug': typeof SiteProdukSlugRoute
  '/artikel': typeof SiteArtikelIndexRoute
  '/produk': typeof SiteProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/keranjang': typeof SiteKeranjangRoute
  '/_site/kontak': typeof SiteKontakRoute
  '/_site/lacak': typeof SiteLacakRoute
  '/_site/tentang': typeof SiteTentangRoute
  '/admin/artikel': typeof AdminArtikelRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/order': typeof AdminOrderRoute
  '/admin/panduan': typeof AdminPanduanRoute
  '/admin/pembayaran': typeof AdminPembayaranRoute
  '/admin/pesan': typeof AdminPesanRoute
  '/admin/produk': typeof AdminProdukRoute
  '/admin/stok': typeof AdminStokRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/artikel/$slug': typeof SiteArtikelSlugRoute
  '/_site/order/$id': typeof SiteOrderIdRoute
  '/_site/produk/$slug': typeof SiteProdukSlugRoute
  '/_site/artikel/': typeof SiteArtikelIndexRoute
  '/_site/produk/': typeof SiteProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/keranjang'
    | '/kontak'
    | '/lacak'
    | '/tentang'
    | '/admin/artikel'
    | '/admin/hero'
    | '/admin/order'
    | '/admin/panduan'
    | '/admin/pembayaran'
    | '/admin/pesan'
    | '/admin/produk'
    | '/admin/stok'
    | '/admin/'
    | '/artikel/$slug'
    | '/order/$id'
    | '/produk/$slug'
    | '/artikel/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sitemap.xml'
    | '/keranjang'
    | '/kontak'
    | '/lacak'
    | '/tentang'
    | '/admin/artikel'
    | '/admin/hero'
    | '/admin/order'
    | '/admin/panduan'
    | '/admin/pembayaran'
    | '/admin/pesan'
    | '/admin/produk'
    | '/admin/stok'
    | '/'
    | '/admin'
    | '/artikel/$slug'
    | '/order/$id'
    | '/produk/$slug'
    | '/artikel'
    | '/produk'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/login'
    | '/sitemap.xml'
    | '/_site/keranjang'
    | '/_site/kontak'
    | '/_site/lacak'
    | '/_site/tentang'
    | '/admin/artikel'
    | '/admin/hero'
    | '/admin/order'
    | '/admin/panduan'
    | '/admin/pembayaran'
    | '/admin/pesan'
    | '/admin/produk'
    | '/admin/stok'
    | '/_site/'
    | '/admin/'
    | '/_site/artikel/$slug'
    | '/_site/order/$id'
    | '/_site/produk/$slug'
    | '/_site/artikel/'
    | '/_site/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/stok': {
      id: '/admin/stok'
      path: '/stok'
      fullPath: '/admin/stok'
      preLoaderRoute: typeof AdminStokRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produk': {
      id: '/admin/produk'
      path: '/produk'
      fullPath: '/admin/produk'
      preLoaderRoute: typeof AdminProdukRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pesan': {
      id: '/admin/pesan'
      path: '/pesan'
      fullPath: '/admin/pesan'
      preLoaderRoute: typeof AdminPesanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pembayaran': {
      id: '/admin/pembayaran'
      path: '/pembayaran'
      fullPath: '/admin/pembayaran'
      preLoaderRoute: typeof AdminPembayaranRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/panduan': {
      id: '/admin/panduan'
      path: '/panduan'
      fullPath: '/admin/panduan'
      preLoaderRoute: typeof AdminPanduanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order': {
      id: '/admin/order'
      path: '/order'
      fullPath: '/admin/order'
      preLoaderRoute: typeof AdminOrderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artikel': {
      id: '/admin/artikel'
      path: '/artikel'
      fullPath: '/admin/artikel'
      preLoaderRoute: typeof AdminArtikelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/tentang': {
      id: '/_site/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof SiteTentangRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lacak': {
      id: '/_site/lacak'
      path: '/lacak'
      fullPath: '/lacak'
      preLoaderRoute: typeof SiteLacakRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kontak': {
      id: '/_site/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof SiteKontakRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/keranjang': {
      id: '/_site/keranjang'
      path: '/keranjang'
      fullPath: '/keranjang'
      preLoaderRoute: typeof SiteKeranjangRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/produk/': {
      id: '/_site/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof SiteProdukIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/artikel/': {
      id: '/_site/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof SiteArtikelIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/produk/$slug': {
      id: '/_site/produk/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof SiteProdukSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/order/$id': {
      id: '/_site/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof SiteOrderIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/artikel/$slug': {
      id: '/_site/artikel/$slug'
      path: '/artikel/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof SiteArtikelSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteKeranjangRoute: typeof SiteKeranjangRoute
  SiteKontakRoute: typeof SiteKontakRoute
  SiteLacakRoute: typeof SiteLacakRoute
  SiteTentangRoute: typeof SiteTentangRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteArtikelSlugRoute: typeof SiteArtikelSlugRoute
  SiteOrderIdRoute: typeof SiteOrderIdRoute
  SiteProdukSlugRoute: typeof SiteProdukSlugRoute
  SiteArtikelIndexRoute: typeof SiteArtikelIndexRoute
  SiteProdukIndexRoute: typeof SiteProdukIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteKeranjangRoute: SiteKeranjangRoute,
  SiteKontakRoute: SiteKontakRoute,
  SiteLacakRoute: SiteLacakRoute,
  SiteTentangRoute: SiteTentangRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteArtikelSlugRoute: SiteArtikelSlugRoute,
  SiteOrderIdRoute: SiteOrderIdRoute,
  SiteProdukSlugRoute: SiteProdukSlugRoute,
  SiteArtikelIndexRoute: SiteArtikelIndexRoute,
  SiteProdukIndexRoute: SiteProdukIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminArtikelRoute: typeof AdminArtikelRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminOrderRoute: typeof AdminOrderRoute
  AdminPanduanRoute: typeof AdminPanduanRoute
  AdminPembayaranRoute: typeof AdminPembayaranRoute
  AdminPesanRoute: typeof AdminPesanRoute
  AdminProdukRoute: typeof AdminProdukRoute
  AdminStokRoute: typeof AdminStokRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtikelRoute: AdminArtikelRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminOrderRoute: AdminOrderRoute,
  AdminPanduanRoute: AdminPanduanRoute,
  AdminPembayaranRoute: AdminPembayaranRoute,
  AdminPesanRoute: AdminPesanRoute,
  AdminProdukRoute: AdminProdukRoute,
  AdminStokRoute: AdminStokRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
